[2023-06-26T18:57:25.236+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-26T18:52:04.674534+00:00 [queued]>
[2023-06-26T18:57:25.244+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-26T18:52:04.674534+00:00 [queued]>
[2023-06-26T18:57:25.245+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-26T18:57:25.248+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-06-26T18:57:25.250+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-26T18:57:25.260+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-06-26 18:52:04.674534+00:00
[2023-06-26T18:57:25.267+0000] {standard_task_runner.py:55} INFO - Started process 27093 to run task
[2023-06-26T18:57:25.272+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-06-26T18:52:04.674534+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpg71twe26']
[2023-06-26T18:57:25.276+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask get_input_data
[2023-06-26T18:57:25.385+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-26T18:52:04.674534+00:00 [running]> on host 635f1a4ac995
[2023-06-26T18:57:25.452+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-26T18:52:04.674534+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-26T18:52:04.674534+00:00
[2023-06-26T18:57:25.456+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-26T18:57:25.458+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target DEV --vars '{'env': 'DEV'}' "]
[2023-06-26T18:57:25.476+0000] {subprocess.py:86} INFO - Output:
[2023-06-26T18:57:26.953+0000] {subprocess.py:93} INFO - [0m18:57:26  Running with dbt=1.5.1
[2023-06-26T18:57:26.970+0000] {subprocess.py:93} INFO - [0m18:57:26  Encountered an error:
[2023-06-26T18:57:26.972+0000] {subprocess.py:93} INFO - Runtime Error
[2023-06-26T18:57:26.976+0000] {subprocess.py:93} INFO -   The profile 'dbt_dsg_app' does not have a target named 'DEV'. The valid target names for this profile are:
[2023-06-26T18:57:26.978+0000] {subprocess.py:93} INFO -    - dev
[2023-06-26T18:57:27.295+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-26T18:57:27.310+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-26T18:57:27.314+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230626T185204, start_date=20230626T185725, end_date=20230626T185727
[2023-06-26T18:57:27.326+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 64 for task get_input_data (Bash command failed. The command returned a non-zero exit code 2.; 27093)
[2023-06-26T18:57:27.356+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-26T18:57:27.379+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
