[2023-06-21T01:19:27.998+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.cleanup_tables manual__2023-06-21T01:17:13.639585+00:00 [queued]>
[2023-06-21T01:19:28.053+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.cleanup_tables manual__2023-06-21T01:17:13.639585+00:00 [queued]>
[2023-06-21T01:19:28.054+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-21T01:19:28.055+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-21T01:19:28.057+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-21T01:19:28.066+0000] {taskinstance.py:1304} INFO - Executing <Task(SnowflakeOperator): cleanup_tables> on 2023-06-21 01:17:13.639585+00:00
[2023-06-21T01:19:28.074+0000] {standard_task_runner.py:55} INFO - Started process 30616 to run task
[2023-06-21T01:19:28.081+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'cleanup_tables', 'manual__2023-06-21T01:17:13.639585+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpcvz6r59q']
[2023-06-21T01:19:28.092+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask cleanup_tables
[2023-06-21T01:19:28.172+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.cleanup_tables manual__2023-06-21T01:17:13.639585+00:00 [running]> on host 635f1a4ac995
[2023-06-21T01:19:28.231+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=cleanup_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-06-21T01:17:13.639585+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-21T01:17:13.639585+00:00
[2023-06-21T01:19:28.234+0000] {sql.py:253} INFO - Executing: ['truncate table DEV_QA.DBT_POC.STG_IPFLOW_INPUT_DATA;', 'truncate table DEV_IP_FLOW.RAW_DATA.IP_FLOW_API_OUTPUT_DATA;', 'truncate table DEV_QA.DBT_POC.stg_ipflow_success_data;', 'truncate table DEV_QA.DBT_POC.src_ipflow_normalized_location;']
[2023-06-21T01:19:28.264+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 254, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `Airflow-Transform-connection` isn't defined
[2023-06-21T01:19:28.271+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=cleanup_tables, execution_date=20230621T011713, start_date=20230621T011928, end_date=20230621T011928
[2023-06-21T01:19:28.280+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task cleanup_tables (The conn_id `Airflow-Transform-connection` isn't defined; 30616)
[2023-06-21T01:19:28.334+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-21T01:19:28.351+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
