[2023-06-20T18:37:26.935+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T18:37:26.996+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T18:37:27.002+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T18:37:27.006+0000] {taskinstance.py:1284} INFO - Starting attempt 7 of 7
[2023-06-20T18:37:27.008+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T18:37:27.028+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-19 00:00:00+00:00
[2023-06-20T18:37:27.042+0000] {standard_task_runner.py:55} INFO - Started process 4842 to run task
[2023-06-20T18:37:27.077+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'scheduled__2023-06-19T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp_wrgcclz']
[2023-06-20T18:37:27.085+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask dbt_run
[2023-06-20T18:37:27.317+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-06-20T18:37:27.453+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-19T00:00:00+00:00
[2023-06-20T18:37:27.469+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T18:37:27.473+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dbt_venv/bin/dbt && dbt run --models .']
[2023-06-20T18:37:27.531+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T18:37:27.582+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 3: import: command not found
[2023-06-20T18:37:27.586+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 4: import: command not found
[2023-06-20T18:37:27.609+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 5: from: command not found
[2023-06-20T18:37:27.616+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 7: syntax error near unexpected token `('
[2023-06-20T18:37:27.618+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 7: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
[2023-06-20T18:37:27.621+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-20T18:37:27.657+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-20T18:37:27.670+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230619T000000, start_date=20230620T183726, end_date=20230620T183727
[2023-06-20T18:37:27.697+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4842)
[2023-06-20T18:37:27.740+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T18:37:27.789+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
