[2023-08-04T16:36:15.195+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T16:22:40.718335+00:00 [queued]>
[2023-08-04T16:36:15.204+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T16:22:40.718335+00:00 [queued]>
[2023-08-04T16:36:15.205+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:36:15.207+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 5
[2023-08-04T16:36:15.208+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:36:15.217+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-04 16:22:40.718335+00:00
[2023-08-04T16:36:15.224+0000] {standard_task_runner.py:55} INFO - Started process 1072 to run task
[2023-08-04T16:36:15.228+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-08-04T16:22:40.718335+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp1hhq_7l8']
[2023-08-04T16:36:15.231+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask get_input_data
[2023-08-04T16:36:15.295+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T16:22:40.718335+00:00 [running]> on host 68b6c38d20d3
[2023-08-04T16:36:15.349+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-04T16:22:40.718335+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-04T16:22:40.718335+00:00
[2023-08-04T16:36:15.353+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T16:36:15.355+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "source /tmp/dbt_venv/bin/activate &&  dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T16:36:15.370+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T16:36:15.372+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /tmp/dbt_venv/bin/activate: No such file or directory
[2023-08-04T16:36:15.373+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-04T16:36:15.386+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-04T16:36:15.390+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230804T162240, start_date=20230804T163615, end_date=20230804T163615
[2023-08-04T16:36:15.401+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 1072)
[2023-08-04T16:36:15.442+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T16:36:15.461+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
