[2023-06-22T00:46:19.795+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-06-21T00:00:00+00:00 [queued]>
[2023-06-22T00:46:19.803+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-06-21T00:00:00+00:00 [queued]>
[2023-06-22T00:46:19.805+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T00:46:19.806+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-22T00:46:19.807+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T00:46:19.819+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-06-21 00:00:00+00:00
[2023-06-22T00:46:19.826+0000] {standard_task_runner.py:55} INFO - Started process 5843 to run task
[2023-06-22T00:46:19.831+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-06-21T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpngynp8ym']
[2023-06-22T00:46:19.834+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask get_input_data
[2023-06-22T00:46:19.907+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-06-21T00:00:00+00:00 [running]> on host 635f1a4ac995
[2023-06-22T00:46:19.974+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-21T00:00:00+00:00
[2023-06-22T00:46:19.977+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T00:46:19.978+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app']
[2023-06-22T00:46:19.994+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T00:46:22.190+0000] {subprocess.py:93} INFO - [0m00:46:22  Running with dbt=1.5.1
[2023-06-22T00:46:22.977+0000] {subprocess.py:93} INFO - [0m00:46:22  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T00:46:22.983+0000] {subprocess.py:93} INFO - [0m00:46:22
[2023-06-22T00:46:25.225+0000] {subprocess.py:93} INFO - [0m00:46:25  Concurrency: 4 threads (target='dev')
[2023-06-22T00:46:25.233+0000] {subprocess.py:93} INFO - [0m00:46:25
[2023-06-22T00:46:25.255+0000] {subprocess.py:93} INFO - [0m00:46:25  1 of 1 START sql table model DBT_POC.stg_ipflow_input_data ..................... [RUN]
[2023-06-22T02:28:17.524+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-06-22T02:28:17.527+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5843. PIDs of all processes in the group: [5844, 5843]
[2023-06-22T02:28:17.529+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5843
[2023-06-22T02:28:17.531+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-22T02:28:17.532+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-06-22T02:28:17.583+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5843, status='terminated', exitcode=0, started='00:46:19') (5843) terminated with exit code 0
[2023-06-22T02:28:17.585+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5844, status='terminated', started='00:46:19') (5844) terminated with exit code None
