[2023-06-21T01:16:31.542+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-21T01:16:29.640211+00:00 [queued]>
[2023-06-21T01:16:31.550+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-21T01:16:29.640211+00:00 [queued]>
[2023-06-21T01:16:31.551+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-21T01:16:31.559+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-21T01:16:31.560+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-21T01:16:31.569+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-06-21 01:16:29.640211+00:00
[2023-06-21T01:16:31.578+0000] {standard_task_runner.py:55} INFO - Started process 30315 to run task
[2023-06-21T01:16:31.583+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-06-21T01:16:29.640211+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmppjqf122x']
[2023-06-21T01:16:31.586+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask get_input_data
[2023-06-21T01:16:31.667+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-06-21T01:16:29.640211+00:00 [running]> on host 635f1a4ac995
[2023-06-21T01:16:31.736+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-21T01:16:29.640211+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-21T01:16:29.640211+00:00
[2023-06-21T01:16:31.739+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-21T01:16:31.741+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app']
[2023-06-21T01:16:31.770+0000] {subprocess.py:86} INFO - Output:
[2023-06-21T01:16:33.506+0000] {subprocess.py:93} INFO - [0m01:16:33  Running with dbt=1.5.1
[2023-06-21T01:16:34.354+0000] {subprocess.py:93} INFO - [0m01:16:34  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-21T01:16:34.361+0000] {subprocess.py:93} INFO - [0m01:16:34
[2023-06-21T01:16:36.192+0000] {subprocess.py:93} INFO - [0m01:16:36  Concurrency: 4 threads (target='dev')
[2023-06-21T01:16:36.198+0000] {subprocess.py:93} INFO - [0m01:16:36
[2023-06-21T01:16:36.223+0000] {subprocess.py:93} INFO - [0m01:16:36  1 of 1 START sql table model DBT_POC.stg_ipflow_input_data ..................... [RUN]
[2023-06-21T01:16:57.179+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-06-21T01:16:57.195+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 30315. PIDs of all processes in the group: [30316, 30315]
[2023-06-21T01:16:57.200+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 30315
[2023-06-21T01:16:57.218+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-21T01:16:57.230+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-06-21T01:16:57.391+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=30315, status='terminated', exitcode=0, started='01:16:31') (30315) terminated with exit code 0
[2023-06-21T01:16:57.407+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=30316, status='terminated', started='01:16:31') (30316) terminated with exit code None
