[2023-08-04T17:37:53.599+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:37:53.606+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T17:37:53.612+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:37:53.614+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-08-04T17:37:53.615+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:37:53.624+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T17:37:53.632+0000] {standard_task_runner.py:55} INFO - Started process 337 to run task
[2023-08-04T17:37:53.637+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmp98lcp2xh']
[2023-08-04T17:37:53.640+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask get_input_data
[2023-08-04T17:37:53.714+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 9817f6d599e1
[2023-08-04T17:37:53.772+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T17:37:53.775+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:37:53.778+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "cd /tmp && source /dbt_venv/bin/activate && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:37:53.794+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:37:53.797+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /dbt_venv/bin/activate: No such file or directory
[2023-08-04T17:37:53.799+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-04T17:37:53.813+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-04T17:37:53.817+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T173753, end_date=20230804T173753
[2023-08-04T17:37:53.837+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task get_input_data (Bash command failed. The command returned a non-zero exit code 1.; 337)
[2023-08-04T17:37:53.891+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:37:53.909+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-04T18:14:07.750+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:14:07.758+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [queued]>
[2023-08-04T18:14:07.759+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:14:07.760+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-08-04T18:14:07.762+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T18:14:07.770+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-03 00:00:00+00:00
[2023-08-04T18:14:07.778+0000] {standard_task_runner.py:55} INFO - Started process 406 to run task
[2023-08-04T18:14:07.783+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'scheduled__2023-08-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpnq01oupd']
[2023-08-04T18:14:07.790+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask get_input_data
[2023-08-04T18:14:07.858+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data scheduled__2023-08-03T00:00:00+00:00 [running]> on host 2d3cfeb384b0
[2023-08-04T18:14:07.914+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-03T00:00:00+00:00
[2023-08-04T18:14:07.917+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T18:14:07.918+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "pip install dbt-snowflake && dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T18:14:07.943+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T18:14:08.403+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-08-04T18:14:08.514+0000] {subprocess.py:93} INFO - Requirement already satisfied: dbt-snowflake in /home/***/.local/lib/python3.7/site-packages (1.5.1)
[2023-08-04T18:14:08.518+0000] {subprocess.py:93} INFO - Requirement already satisfied: dbt-core~=1.5.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-snowflake) (1.5.4)
[2023-08-04T18:14:08.519+0000] {subprocess.py:93} INFO - Requirement already satisfied: snowflake-connector-python[secure-local-storage]~=3.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-snowflake) (3.0.4)
[2023-08-04T18:14:08.533+0000] {subprocess.py:93} INFO - Requirement already satisfied: Jinja2==3.1.2 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (3.1.2)
[2023-08-04T18:14:08.535+0000] {subprocess.py:93} INFO - Requirement already satisfied: agate<1.7.1,>=1.6 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (1.7.0)
[2023-08-04T18:14:08.536+0000] {subprocess.py:93} INFO - Requirement already satisfied: click<8.1.4,>=7.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (8.1.3)
[2023-08-04T18:14:08.537+0000] {subprocess.py:93} INFO - Requirement already satisfied: colorama<0.4.7,>=0.3.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.4.4)
[2023-08-04T18:14:08.538+0000] {subprocess.py:93} INFO - Requirement already satisfied: hologram<=0.0.16,>=0.0.14 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.0.16)
[2023-08-04T18:14:08.539+0000] {subprocess.py:93} INFO - Requirement already satisfied: isodate<0.7,>=0.6 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.6.1)
[2023-08-04T18:14:08.542+0000] {subprocess.py:93} INFO - Requirement already satisfied: logbook<1.6,>=1.5 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (1.5.3)
[2023-08-04T18:14:08.543+0000] {subprocess.py:93} INFO - Requirement already satisfied: mashumaro[msgpack]==3.6 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (3.6)
[2023-08-04T18:14:08.554+0000] {subprocess.py:93} INFO - Requirement already satisfied: minimal-snowplow-tracker==0.0.2 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.0.2)
[2023-08-04T18:14:08.557+0000] {subprocess.py:93} INFO - Requirement already satisfied: packaging>20.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (21.3)
[2023-08-04T18:14:08.559+0000] {subprocess.py:93} INFO - Requirement already satisfied: sqlparse>=0.2.3 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.4.3)
[2023-08-04T18:14:08.560+0000] {subprocess.py:93} INFO - Requirement already satisfied: dbt-extractor~=0.4.1 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.4.1)
[2023-08-04T18:14:08.561+0000] {subprocess.py:93} INFO - Requirement already satisfied: typing-extensions>=3.7.4 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (4.4.0)
[2023-08-04T18:14:08.562+0000] {subprocess.py:93} INFO - Requirement already satisfied: werkzeug<3,>=1 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2.2.2)
[2023-08-04T18:14:08.563+0000] {subprocess.py:93} INFO - Requirement already satisfied: pathspec<0.12,>=0.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (0.9.0)
[2023-08-04T18:14:08.600+0000] {subprocess.py:93} INFO - Requirement already satisfied: protobuf>=4.0.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (4.23.4)
[2023-08-04T18:14:08.603+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz>=2015.7 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2022.6)
[2023-08-04T18:14:08.604+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests<3.0.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2.28.1)
[2023-08-04T18:14:08.608+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (3.4)
[2023-08-04T18:14:08.615+0000] {subprocess.py:93} INFO - Requirement already satisfied: cffi<2.0.0,>=1.9 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (1.15.1)
[2023-08-04T18:14:08.617+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyyaml>=6.0 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (6.0.1)
[2023-08-04T18:14:08.619+0000] {subprocess.py:93} INFO - Requirement already satisfied: networkx<2.8.1,>=2.3 in /home/***/.local/lib/python3.7/site-packages (from dbt-core~=1.5.0->dbt-snowflake) (2.6.3)
[2023-08-04T18:14:08.620+0000] {subprocess.py:93} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.7/site-packages (from Jinja2==3.1.2->dbt-core~=1.5.0->dbt-snowflake) (2.1.1)
[2023-08-04T18:14:08.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: msgpack>=0.5.6 in /home/***/.local/lib/python3.7/site-packages (from mashumaro[msgpack]==3.6->dbt-core~=1.5.0->dbt-snowflake) (1.0.4)
[2023-08-04T18:14:08.622+0000] {subprocess.py:93} INFO - Requirement already satisfied: six<2.0,>=1.9.0 in /home/***/.local/lib/python3.7/site-packages (from minimal-snowplow-tracker==0.0.2->dbt-core~=1.5.0->dbt-snowflake) (1.16.0)
[2023-08-04T18:14:08.624+0000] {subprocess.py:93} INFO - Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (1.5.1)
[2023-08-04T18:14:08.634+0000] {subprocess.py:93} INFO - Requirement already satisfied: cryptography<41.0.0,>=3.1.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (36.0.2)
[2023-08-04T18:14:08.636+0000] {subprocess.py:93} INFO - Requirement already satisfied: oscrypto<2.0.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (1.3.0)
[2023-08-04T18:14:08.638+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyOpenSSL<24.0.0,>=16.2.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (22.0.0)
[2023-08-04T18:14:08.639+0000] {subprocess.py:93} INFO - Requirement already satisfied: pycryptodomex!=3.5.0,<4.0.0,>=3.2 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.18.0)
[2023-08-04T18:14:08.640+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyjwt<3.0.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2.6.0)
[2023-08-04T18:14:08.641+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2.1.1)
[2023-08-04T18:14:08.643+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (1.26.13)
[2023-08-04T18:14:08.644+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2022.9.24)
[2023-08-04T18:14:08.645+0000] {subprocess.py:93} INFO - Requirement already satisfied: filelock<4,>=3.5 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.8.0)
[2023-08-04T18:14:08.654+0000] {subprocess.py:93} INFO - Requirement already satisfied: sortedcontainers>=2.4.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (2.4.0)
[2023-08-04T18:14:08.655+0000] {subprocess.py:93} INFO - Requirement already satisfied: importlib-metadata in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (4.13.0)
[2023-08-04T18:14:08.657+0000] {subprocess.py:93} INFO - Requirement already satisfied: keyring!=16.1.0,<24.0.0 in /home/***/.local/lib/python3.7/site-packages (from snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (23.13.1)
[2023-08-04T18:14:08.658+0000] {subprocess.py:93} INFO - Requirement already satisfied: Babel>=2.0 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (2.11.0)
[2023-08-04T18:14:08.659+0000] {subprocess.py:93} INFO - Requirement already satisfied: leather>=0.3.2 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (0.3.4)
[2023-08-04T18:14:08.660+0000] {subprocess.py:93} INFO - Requirement already satisfied: parsedatetime!=2.5,!=2.6,>=2.1 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (2.4)
[2023-08-04T18:14:08.661+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify>=1.2.1 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (7.0.0)
[2023-08-04T18:14:08.662+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytimeparse>=1.1.5 in /home/***/.local/lib/python3.7/site-packages (from agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (1.1.8)
[2023-08-04T18:14:08.664+0000] {subprocess.py:93} INFO - Requirement already satisfied: pycparser in /home/***/.local/lib/python3.7/site-packages (from cffi<2.0.0,>=1.9->dbt-core~=1.5.0->dbt-snowflake) (2.21)
[2023-08-04T18:14:08.665+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil<2.9,>=2.8 in /home/***/.local/lib/python3.7/site-packages (from hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (2.8.2)
[2023-08-04T18:14:08.666+0000] {subprocess.py:93} INFO - Requirement already satisfied: jsonschema>=3.0 in /home/***/.local/lib/python3.7/site-packages (from hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (4.17.3)
[2023-08-04T18:14:08.668+0000] {subprocess.py:93} INFO - Requirement already satisfied: jaraco.classes in /home/***/.local/lib/python3.7/site-packages (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.2.3)
[2023-08-04T18:14:08.669+0000] {subprocess.py:93} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.7/site-packages (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (5.10.0)
[2023-08-04T18:14:08.670+0000] {subprocess.py:93} INFO - Requirement already satisfied: SecretStorage>=3.2 in /home/***/.local/lib/python3.7/site-packages (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.3.3)
[2023-08-04T18:14:08.671+0000] {subprocess.py:93} INFO - Requirement already satisfied: jeepney>=0.4.2 in /home/***/.local/lib/python3.7/site-packages (from keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (0.8.0)
[2023-08-04T18:14:08.674+0000] {subprocess.py:93} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.7/site-packages (from importlib-metadata->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (3.11.0)
[2023-08-04T18:14:08.699+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/***/.local/lib/python3.7/site-packages (from packaging>20.9->dbt-core~=1.5.0->dbt-snowflake) (3.0.9)
[2023-08-04T18:14:08.787+0000] {subprocess.py:93} INFO - Requirement already satisfied: attrs>=17.4.0 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.0->hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (22.1.0)
[2023-08-04T18:14:08.790+0000] {subprocess.py:93} INFO - Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.0->hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (1.3.10)
[2023-08-04T18:14:08.791+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.0->hologram<=0.0.16,>=0.0.14->dbt-core~=1.5.0->dbt-snowflake) (0.19.2)
[2023-08-04T18:14:08.814+0000] {subprocess.py:93} INFO - Requirement already satisfied: future in /home/***/.local/lib/python3.7/site-packages (from parsedatetime!=2.5,!=2.6,>=2.1->agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (0.18.2)
[2023-08-04T18:14:08.829+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify>=1.2.1->agate<1.7.1,>=1.6->dbt-core~=1.5.0->dbt-snowflake) (1.3)
[2023-08-04T18:14:08.866+0000] {subprocess.py:93} INFO - Requirement already satisfied: more-itertools in /home/***/.local/lib/python3.7/site-packages (from jaraco.classes->keyring!=16.1.0,<24.0.0->snowflake-connector-python[secure-local-storage]~=3.0->dbt-snowflake) (9.1.0)
[2023-08-04T18:14:11.532+0000] {subprocess.py:93} INFO - 
[2023-08-04T18:14:11.534+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.1.2 -> 23.2.1
[2023-08-04T18:14:11.542+0000] {subprocess.py:93} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-08-04T18:14:13.053+0000] {subprocess.py:93} INFO - [0m18:14:13  Running with dbt=1.5.4
[2023-08-04T18:14:13.542+0000] {subprocess.py:93} INFO - [0m18:14:13  Registered adapter: snowflake=1.5.1
[2023-08-04T18:14:13.911+0000] {subprocess.py:93} INFO - [0m18:14:13  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 322 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-08-04T18:14:13.916+0000] {subprocess.py:93} INFO - [0m18:14:13
[2023-08-04T18:14:15.600+0000] {subprocess.py:93} INFO - [0m18:14:15  Concurrency: 4 threads (target='dev')
[2023-08-04T18:14:15.603+0000] {subprocess.py:93} INFO - [0m18:14:15
[2023-08-04T18:14:15.614+0000] {subprocess.py:93} INFO - [0m18:14:15  1 of 1 START sql table model DBT_POC.stg_ipflow_input_data ..................... [RUN]
[2023-08-04T18:14:18.985+0000] {subprocess.py:93} INFO - [0m18:14:18  1 of 1 OK created sql table model DBT_POC.stg_ipflow_input_data ................ [[32mSUCCESS 1[0m in 3.36s]
[2023-08-04T18:14:19.000+0000] {subprocess.py:93} INFO - [0m18:14:19
[2023-08-04T18:14:19.002+0000] {subprocess.py:93} INFO - [0m18:14:19  Finished running 1 table model in 0 hours 0 minutes and 5.08 seconds (5.08s).
[2023-08-04T18:14:19.060+0000] {subprocess.py:93} INFO - [0m18:14:19
[2023-08-04T18:14:19.062+0000] {subprocess.py:93} INFO - [0m18:14:19  [32mCompleted successfully[0m
[2023-08-04T18:14:19.065+0000] {subprocess.py:93} INFO - [0m18:14:19
[2023-08-04T18:14:19.070+0000] {subprocess.py:93} INFO - [0m18:14:19  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2023-08-04T18:14:19.611+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-04T18:14:19.647+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230803T000000, start_date=20230804T181407, end_date=20230804T181419
[2023-08-04T18:14:19.696+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-08-04T18:14:19.715+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
